general:
  ontology: data/gd/mini_pheno_e.owl
  graph-gen-method: taxonomy
  use-case: gd

rgcn-params:
  lr: 0.00001
  n-hidden: 0
  batch-size: 32
  epochs: 32
  dropout: 0.5
  regularization: 0.0001
  num-bases: -1
  normalization: True
  self-loop: False
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/gd/training_fold0.pickle"
  valid_inter_file: "data/gd/validation_fold0.pickle"
  test_inter_file: "data/gd/testing_fold0.pickle"
  gene_data_file: "data/gd/MGI_Annot.txt"
  disease_data_file: "data/gd/HPO_Annot.txt"
  terms_file: "data/gd/terms.tsv"
  precomputed_edges_file: "data/gd/edges_tax.pkl"
  output_model: "data/gd/tax_model.pt"
