general:
  ontology: data/ppi/go.owl
  graph-gen-method: dl2vec
  use-case: ppi


data-params:
  train-size: -1
  val-size: -1
  test-size: -1


gnn-sim-params:
  lr: 0.000001
  bs: 128
  epochs: 32
  regularization: 0.01
  normalization: True
  self-loop: True
  seed: 0
  min-edges: 0

ppi-model-params:
  siamese: True
  dropout: 0.5
  n-hid: 0
  residual: False
  num-bases: -1

files:
  train_inter_file: "data/ppi/4932.train_interactions.pkl"
  valid_inter_file: "data/ppi/4932.valid_interactions.pkl"
  test_inter_file: "data/ppi/4932.test_interactions.pkl"
  data_file: "data/ppi/4932.annotations.tsv"
  terms_file: "data/ppi/4932.terms.tsv"
  output_model: "data/ppi/dl2vec_yeast_model_hid_0_siam_True_res_False_.pt"

